"""Build a v2RayTun routing profile from a checked-out Grimbird source tree.

Usage: python build-routing.py PATH_TO_RU_ROUTING_DAT
The source checkout is read-only. Generated output is written beside this script.
"""
import base64
import json
from pathlib import Path
import sys
import uuid


def varint(data, offset):
    value = shift = 0
    while True:
        byte = data[offset]
        offset += 1
        value |= (byte & 127) << shift
        if byte < 128:
            return value, offset
        shift += 7


def fields(data):
    """Read wire fields only; enough to verify names in GeoIPList/GeoSiteList."""
    offset = 0
    while offset < len(data):
        tag, offset = varint(data, offset)
        wire = tag & 7
        if wire == 0:
            value, offset = varint(data, offset)
        elif wire == 2:
            size, offset = varint(data, offset)
            value = data[offset:offset + size]
            offset += size
        else:
            raise ValueError(f'Unsupported protobuf wire type: {wire}')
        yield tag >> 3, value


def categories(path):
    names = set()
    for number, entry in fields(path.read_bytes()):
        if number == 1:
            for field, value in fields(entry):
                if field == 1:
                    names.add(value.decode('utf-8').lower())
    return names


def stable_id(name):
    return str(uuid.uuid5(uuid.NAMESPACE_URL, 'singlemate/in-rout/grimbird/' + name)).upper()


root = Path(sys.argv[1])
source = json.loads((root / 'INCY/WHITELIST.JSON').read_text(encoding='utf-8'))
for key, prefix, filename in [('DirectSites', 'geosite:', 'geosite.dat'), ('DirectIp', 'geoip:', 'geoip.dat')]:
    available = categories(root / filename)
    missing = {value[len(prefix):].lower() for value in source[key] if value.startswith(prefix)} - available
    if missing:
        raise ValueError(f'{filename} is missing categories: {sorted(missing)}')

profile = {
    'name': source['Name'],
    'id': stable_id('profile'),
    'domainStrategy': source['DomainStrategy'],
    'domainMatcher': 'hybrid',
    'balancers': [],
    'rules': [
        {'id': stable_id('domains'), '__name__': 'Grimbird whitelist domains', 'type': 'field', 'domain': source['DirectSites'], 'outboundTag': 'direct'},
        {'id': stable_id('ips'), '__name__': 'Grimbird whitelist IPs', 'type': 'field', 'ip': source['DirectIp'], 'outboundTag': 'direct'},
        # IP catch-all preserves IPIfNonMatch resolution, unlike network: tcp,udp.
        {'id': stable_id('default'), '__name__': 'Other IPs via VPN', 'type': 'field', 'ip': ['0.0.0.0/0', '::/0'], 'outboundTag': 'proxy'}
    ]
}
out = Path(__file__).resolve().parent / 'routing'
out.mkdir(exist_ok=True)
payload = json.dumps(profile, ensure_ascii=False, separators=(',', ':'))
deeplink = 'v2raytun://import_route/' + base64.urlsafe_b64encode(payload.encode('utf-8')).decode('ascii')
(out / 'grimbird-whitelist.json').write_text(json.dumps(profile, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
(out / 'grimbird-whitelist-link.txt').write_text(deeplink + '\n', encoding='utf-8')
bundle = {'profile': profile, 'deeplink': deeplink, 'geosite': source['Geositeurl'], 'geoip': source['Geoipurl']}
(out / 'grimbird-whitelist.js').write_text('// Generated by build-routing.py. See README.md for sources and verification limits.\nwindow.GRIMBIRD_ROUTING = ' + json.dumps(bundle, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
print(f'Validated all GeoSite/GeoIP categories. Generated {len(profile["rules"])} rules; deep link: {len(deeplink)} characters.')
